version: '3.9'

services:
  db :
    image: mysql
    volumes:
      - $COMPOSE_DATA_VOLUME:/var/lib/mysql
    restart: always
    ports:
     - 3306:3306
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=$COMPOSE_DATA_PASS
  shop:
    image: online-shop
    ports:
      - 18800-18888:8080
    depends_on:
      - db
    environment:
      - DATA_URL=jdbc:mysql://db:3306/shop
      - DATA_PASS=$COMPOSE_DATA_PASS
      - DATA_NAME=$COMPOSE_USERNAME
      - OPEN_WEATHER_MAP_KEY=$OPEN_WEATHER_MAP_KEY

