CREATE TABLE user (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR (100) NOT NULL UNIQUE,
    password VARCHAR (50) NOT NULL,
    createdAt TIMESTAMP,
    lastModifiedAt TIMESTAMP
);

CREATE TABLE cart (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    userId INTEGER NOT NULL
);

CREATE TABLE cart_item (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    cartId INTEGER NOT NULL,
    itemId INTEGER NOT NULL
);

CREATE TABLE item(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL
);